package com.libraryarc;

/**
 *
 * @author Guce C.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.HashMap;
import java.util.Map;

public class LoginFrame extends javax.swing.JFrame {
    private Map<String, String> users = new HashMap<>();
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        
        //load from "userData.txt"
        loadUserData();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        jLoginButton = new javax.swing.JButton();
        userText = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(175, 255, 175));
        setMinimumSize(new java.awt.Dimension(760, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel.setText("User:");
        getContentPane().add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 100, 30));

        passLabel.setText("Password:");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, 30));

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 160, 30));

        jLoginButton.setText("Confirm Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 170, 40));
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        jLoginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = userText.getText();
                String password = new String(passwordText.getPassword());
                                    

                // Validate the user credentials
                if (validateLogin(username, password)) {
                    java.awt.EventQueue.invokeLater(() -> {                        
                        dispose();
                        new Borrow().setVisible(true);
                    });
                } else {
                    JOptionPane.showMessageDialog(LoginFrame.this, "Invalid username or password.");
                }                
                             
            }
        });
        
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void loadUserData() {
        try (BufferedReader br = new BufferedReader(new FileReader("userData.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split("=");
                if (parts.length == 2) {
                    users.put(parts[0], parts[1]);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading user data.");
        }
    }
    
    private boolean validateLogin(String username, String password) {
        return users.containsKey(username) && users.get(username).equals(password);
    }
    /**
     * @param args the command line arguments
     * TODO: Move main class to main java file (remove it here)
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}


